version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build: ./backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: npm start
  runner:
    build: ./backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: npm run runner