name: 'Weekly Git Lock Check'

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  check-locks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find Git lock files
        run: |
          set -e
          LOCKS=$(git ls-files --others --exclude-standard; true)
          echo "Repository: $(pwd)"
          # Run check script
          chmod +x ./scripts/check-git-locks.sh
          ./scripts/check-git-locks.sh || true
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: git-locks-report
          path: |
            .git/*lock
            .git/refs/**/.*lock
